### ISSUE TITLE
Default Password And User?

### ISSUE THREAD

**Issue by ZandercraftGames** [crcollins/pyOS#2]
I am trying PyOS out, out of curiosity mainly. I get as far as the login and cannot seem to figure out the default username and password. I have tried root; root, root; x, and even my username and password on my pc, yet I still cannot figure it out. Any help with this would be greatly appreciated.

**Comment by crcollins** [comment]
Haha, I also could not remember what I had set for the password almost 10 years ago. But looking at the code, it looks like I just set it to “pass” for root.

But you can set whatever password you want if you change the string in
kernel/userdata.py for root or add a user there. It is just a simple hexdigest of a sha256 hash of the password.
```
>>> import hashlib
>>> hashlib.sha256("somepass").hexdigest()
'045928218d6d5a42f976163d70cdfe9226e9d1c3ea6bf1647ae1d8f44c2edc7d'
```
While you are at it, you may want to remove annoying debug statements (and typos) in
kernel/system.py around line 134.

**Comment by ZandercraftGames** [comment]
> Haha, I also could not remember what I had set for the password almost 10 years ago. But looking at the code, it looks like I just set it to “pass” for root.
> 
> But you can set whatever password you want if you change the string in
> kernel/userdata.py for root or add a user there. It is just a simple hexdigest of a sha256 hash of the password.
> 
> ```
> >>> import hashlib
> >>> hashlib.sha256("somepass").hexdigest()
> '045928218d6d5a42f976163d70cdfe9226e9d1c3ea6bf1647ae1d8f44c2edc7d'
> ```
> 
> While you are at it, you may want to remove annoying debug statements (and typos) in
> kernel/system.py around line 134.

Thanks man, lol. It looks very cool. Kinda sad that you stopped developing it, but I understand.

**Comment by crcollins** [comment]
Eh, it was just to scratch an itch and learn a few things. As #1 points out, there are some limitations to doing something like this if you wanted to make it a real OS. So, it is more of a play thing.
